services:
  app:
    build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TZ=Europe/Kyiv
      - DATABASE_URL=${DATABASE_URL}
      - SALTROUNDS=${SALTROUNDS}
      - DEPLOYNAME=${DEPLOYNAME}
      - TGBOTKEY=${TGBOTKEY}
      - NUTUPSNAME=${NUTUPSNAME}
    volumes:
      - ./storage.db:/app/prisma/storage.db
      - /var/run/nut:/var/run/nut:ro
